// Generated by @rezejs/router/vite. Do not edit.
declare module "virtual:reze-routes" {
  import type { RouteDefinition } from "@rezejs/router";
  export const routes: readonly RouteDefinition[];
}
declare module "virtual:reze-routes/register" {
  module "@rezejs/router" {
    interface Register {
      paths: "/" | "/about" | "/blog" | "/login" | `/blog/${string}`;
    }
  }
}
