// Generated by @rezejs/vite-plugin. Do not edit.
declare module "virtual:reze-routes" {
  import type { PathsTree, RouteDefinition } from "@rezejs/router";
  export const routes: readonly RouteDefinition[];
  export const paths: PathsTree;
}
declare module "virtual:reze-routes/register" {
  import type { DataOf } from "@rezejs/router";
  import type { SearchInit } from "@rezejs/router";
  import type { HrefFor } from "@rezejs/router";
  module "@rezejs/router" {
    interface Register {
      paths: "/" | "/about" | "/blog" | "/login" | `/blog/${string}`;
      base: "";
      routes: {
        "/login": { params: {}; data: DataOf<import("./routes/(auth)/login")> };
        "/*404": { params: { readonly "404": string }; data: DataOf<import("./routes/[...404]")> };
        "/about": { params: {}; data: DataOf<import("./routes/about")> };
        "/blog/:id": { params: { readonly "id": string }; data: DataOf<import("./routes/blog/[id]")> };
        "/blog": { params: {}; data: DataOf<import("./routes/blog/index")> };
        "/": { params: {}; data: DataOf<import("./routes/index")> };
      };
      pathsTree: { readonly "login": { (search?: SearchInit, hash?: string): HrefFor<"/login"> }; readonly "by404": { (parts?: string | readonly (string | number)[], search?: SearchInit, hash?: string): HrefFor<"/"> }; readonly "about": { (search?: SearchInit, hash?: string): HrefFor<"/about"> }; readonly "blog": { (search?: SearchInit, hash?: string): HrefFor<"/blog">; readonly "byId": { (value: string | number, search?: SearchInit, hash?: string): HrefFor<`/blog/${string}`> }; readonly "index": { (search?: SearchInit, hash?: string): HrefFor<"/blog"> } }; readonly "index": { (search?: SearchInit, hash?: string): HrefFor<"/"> } };
    }
  }
}
