import { posix } from "node:path";

import type { FileRoute } from "./scan";

const StringType = "${string}";

/** The `virtual:reze-routes` module: a nested route table importing each file under `dir` (absolute) lazily. */
export function routesModule(routes: readonly FileRoute[], dir: string): string {
  const root = dir.replace(/\\/g, "/");
  const emit = (list: readonly FileRoute[]): string =>
    "[" +
    list
      .map(
        (route) =>
          `{ path: ${JSON.stringify(route.path)}, load: () => import(${JSON.stringify(posix.join(root, route.file))})` +
          (route.children.length > 0 ? `, children: ${emit(route.children)}` : "") +
          " }",
      )
      .join(", ") +
    "]";
  return `export const routes = ${emit(routes)};\n`;
}

function escapeTemplate(text: string): string {
  return text.replace(/[`\\]|\$\{/g, (match) => "\\" + match);
}

/** Href shapes of `fullPath`; a splat without a static segment before it (a catch-all) adds no `${string}` shape. */
function hrefVariants(fullPath: string): string[][] {
  let variants: string[][] = [[]];
  let hasStatic = false;
  for (const segment of fullPath.split("/")) {
    if (segment === "") continue;
    const head = segment[0];
    if (head === "*" && !hasStatic) continue;
    if (head === "*" || (head === ":" && segment.endsWith("?"))) {
      variants = [...variants, ...variants.map((parts) => [...parts, StringType])];
    } else {
      hasStatic ||= head !== ":";
      const part = head === ":" ? StringType : segment;
      variants = variants.map((parts) => [...parts, part]);
    }
  }
  return variants;
}

function renderPath(parts: readonly string[]): string {
  if (!parts.includes(StringType)) return JSON.stringify("/" + parts.join("/"));
  return "`/" + parts.map((part) => (part === StringType ? part : escapeTemplate(part))).join("/") + "`";
}

function collectPaths(routes: readonly FileRoute[], paths: Set<string>): void {
  for (const route of routes) {
    if (route.children.length > 0) collectPaths(route.children, paths);
    else for (const parts of hrefVariants(route.fullPath)) paths.add(renderPath(parts));
  }
}

/** The generated `.d.ts`: types `virtual:reze-routes` and registers every leaf route path plus `base`, the prefix `<a href>` puts before a route path. */
export function routesDts(routes: readonly FileRoute[], base: string): string {
  const set = new Set<string>();
  collectPaths(routes, set);
  const paths = set.size === 0 ? "never" : [...set].sort().join(" | ");
  return `// Generated by @rezejs/router/vite. Do not edit.
declare module "virtual:reze-routes" {
  import type { RouteDefinition } from "@rezejs/router";
  export const routes: readonly RouteDefinition[];
}
declare module "virtual:reze-routes/register" {
  module "@rezejs/router" {
    interface Register {
      paths: ${paths};
      base: ${JSON.stringify(base)};
    }
  }
}
`;
}
