import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import type { Plugin, ResolvedConfig } from "vite";
import { afterEach, beforeEach, expect, test, vi } from "vitest";

import reze, { type FileRoutesOptions, type Options } from "../src";

const compile = vi.hoisted(() => vi.fn());
vi.mock("@rezejs/compiler", () => ({ compile }));

let root: string;

beforeEach(() => {
  compile.mockReset();
  compile.mockReturnValue({ code: "out", map: undefined, diagnostics: [] });
  root = mkdtempSync(join(tmpdir(), "reze-file-routes-"));
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

const baseConfig = {
  command: "build",
  isProduction: true,
  server: {},
};

const clientEnvironment = {
  consumer: "client",
  dev: { sourcemap: { js: true } },
  build: { sourcemap: false },
};

interface RoutesHooks {
  configResolved(config: ResolvedConfig): void;
  buildStart(): void;
  resolveId(id: string): string | undefined;
  load(id: string): string | undefined;
}

async function start(
  options: Options & { fileRoutes: true | FileRoutesOptions },
  base = "/",
): Promise<{ plugins: Plugin[]; routes: RoutesHooks }> {
  const plugins = await reze(options);
  const config = { ...baseConfig, root, base, plugins } as unknown as ResolvedConfig;
  for (const plugin of plugins) {
    (plugin.configResolved as unknown as ((config: ResolvedConfig) => void) | undefined)?.(config);
  }
  const routes = plugins.find((plugin) => plugin.name === "reze-router") as unknown as RoutesHooks;
  return { plugins, routes };
}

function writeRoutes(dir: string): void {
  mkdirSync(join(dir, "blog"), { recursive: true });
  writeFileSync(join(dir, "index.tsx"), "");
  writeFileSync(join(dir, "blog", "[id].tsx"), "");
}

function transform(plugins: Plugin[], code: string, id: string): unknown {
  const plugin = plugins.find((item) => item.name === "reze-js")!;
  const hook = plugin.transform as { handler: (code: string, id: string) => unknown };
  return hook.handler.call({ environment: { config: clientEnvironment }, warn: vi.fn() }, code, id);
}

async function registeredBase(fileRoutes: true | FileRoutesOptions, base: string): Promise<string | undefined> {
  mkdirSync(join(root, "src", "routes"), { recursive: true });
  writeFileSync(join(root, "src", "routes", "index.tsx"), "");
  const { routes } = await start({ fileRoutes }, base);
  routes.buildStart();
  return /base: (".*");/.exec(readFileSync(join(root, "src", "routes.gen.d.ts"), "utf8"))?.[1];
}

test.each([
  ["/app/", '"/app"'],
  ["./", '""'],
  ["https://cdn.test/assets/", '""'],
])("Vite base %j registers the href base the browser history uses", async (base, registered) => {
  expect(await registeredBase(true, base)).toBe(registered);
});

test('history: "hash" registers "#" as the href base whatever Vite\'s base', async () => {
  expect(await registeredBase({ history: "hash" }, "/app/")).toBe('"#"');
});

test("claims native anchors for the router", async () => {
  writeRoutes(join(root, "src", "routes"));
  const { plugins, routes } = await start({ fileRoutes: true });
  routes.buildStart();
  transform(plugins, "src", "/src/App.tsx");
  expect(compile.mock.calls[0]![2]).toMatchObject({ links: "@rezejs/router" });
});

test("links: false leaves anchors to the explicit module", async () => {
  writeRoutes(join(root, "src", "routes"));
  const { plugins, routes } = await start({ links: "@rezejs/other", fileRoutes: { links: false } });
  routes.buildStart();
  transform(plugins, "src", "/src/App.tsx");
  expect(compile.mock.calls[0]![2]).toMatchObject({ links: "@rezejs/other" });
});

test("serves the scanned routes as a virtual module and writes the declaration file", async () => {
  const dir = join(root, "src", "routes");
  writeRoutes(dir);
  const { routes } = await start({ fileRoutes: true });
  routes.buildStart();
  const id = routes.resolveId("virtual:reze-routes")!;
  const posixDir = dir.replaceAll("\\", "/");
  expect(routes.load(id)).toContain(
    `export const routes = [{ path: "/blog/:id", load: () => import(${JSON.stringify(posixDir + "/blog/[id].tsx")}) }, ` +
      `{ path: "/", load: () => import(${JSON.stringify(posixDir + "/index.tsx")}) }];`,
  );
  expect(routes.load(id)).toContain('export const paths = { "byId": (value, search, hash) => href(`/blog/${enc(value)}`, search, hash)');
  expect(routes.resolveId("other")).toBeUndefined();
  expect(readFileSync(join(root, "src", "routes.gen.d.ts"), "utf8")).toContain("// Generated by @rezejs/vite-plugin. Do not edit.");
});

test("a custom dir without declarations serves routes only", async () => {
  const dir = join(root, "pages");
  writeRoutes(dir);
  const { routes } = await start({ fileRoutes: { dir: "pages", dts: false } });
  routes.buildStart();
  const id = routes.resolveId("virtual:reze-routes")!;
  expect(routes.load(id)).toContain('path: "/blog/:id"');
  expect(existsSync(join(root, "src", "routes.gen.d.ts"))).toBe(false);
});

test("a missing routes directory throws", async () => {
  const { routes } = await start({ fileRoutes: true });
  expect(() => routes.buildStart()).toThrow(`[reze-router] routes directory not found: ${join(root, "src", "routes")}`);
});

test("without fileRoutes returns the single reze plugin", () => {
  const plugin = reze();
  expect(plugin).not.toBeInstanceOf(Promise);
  expect(plugin.name).toBe("reze-js");
});
