import { rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { expect, test } from "vite-plus/test";

import { routesDts, routesModule } from "../src/fs/codegen";
import { scanRoutes } from "../src/fs/scan";

const dtsFile = "/app/src/routes.gen.d.ts";
const routesDir = "/app/src/routes";

function dts(files: readonly string[], base = "/app"): string {
  return routesDts(scanRoutes(files), base, dtsFile, routesDir);
}

test("routesDts registers hrefs and the base", () => {
  const out = dts(["index.tsx", "blog/[id].tsx", "archive/[[page]].tsx", "docs/[...path].tsx"]);
  expect(out).toContain('paths: "/" | "/archive" | "/docs" | `/archive/${string}` | `/blog/${string}` | `/docs/${string}`;');
  expect(out).toContain('base: "/app";');
});

test("a catch-all splat registers only its prefix so hrefs stay checked", () => {
  expect(dts(["[...404].tsx", "docs/[...path].tsx"], "")).toContain('paths: "/" | "/docs" | `/docs/${string}`;');
});

test("routesDts escapes template characters and falls back to never", () => {
  expect(dts(["a`b/[id].tsx"], "")).toContain("paths: `/a\\`b/${string}`;");
  expect(routesDts([], "", dtsFile, routesDir)).toContain("paths: never;");
});

test("routesDts registers leaf params and data from the route files", () => {
  const out = dts(["index.tsx", "blog/[id].tsx", "archive/[[page]].tsx", "docs/[...path].tsx"]);
  expect(out).toContain('"/": { params: {}; data: DataOf<import("./routes/index")> };');
  expect(out).toContain('"/blog/:id": { params: { readonly "id": string }; data: DataOf<import("./routes/blog/[id]")> };');
  expect(out).toContain('"/archive/:page?": { params: { readonly "page"?: string }; data: DataOf<import("./routes/archive/[[page]]")> };');
  expect(out).toContain('"/docs/*path": { params: { readonly "path": string }; data: DataOf<import("./routes/docs/[...path]")> };');
});

test("routesDts keeps the file extension for non-script routes", () => {
  const routes = scanRoutes(["index.mdx", "guide.md"], { extensions: ["mdx", ".md"] });
  const out = routesDts(routes, "", dtsFile, routesDir);
  expect(out).toContain('"/guide": { params: {}; data: DataOf<import("./routes/guide.md")> };');
  expect(out).toContain('"/": { params: {}; data: DataOf<import("./routes/index.mdx")> };');
});

test("routesDts registers the paths builders with precise href returns", () => {
  const out = dts(["index.tsx", "blog.tsx", "blog/[id].tsx", "blog/index.tsx", "archive/[[page]].tsx", "docs/[...path].tsx"]);
  expect(out).toContain('readonly "index": { (search?: SearchInit, hash?: string): HrefFor<"/app/"> }');
  expect(out).toContain(
    'readonly "blog": { (search?: SearchInit, hash?: string): HrefFor<"/app/blog">; readonly "byId": { (value: string | number, search?: SearchInit, hash?: string): HrefFor<`/app/blog/${string}`> }; readonly "index": { (search?: SearchInit, hash?: string): HrefFor<"/app/blog"> } }',
  );
  expect(out).toContain(
    'readonly "byPage": { (value?: string | number, search?: SearchInit, hash?: string): HrefFor<"/app/archive"> | HrefFor<`/app/archive/${string}`> }',
  );
  expect(out).toContain('readonly "byPath": { (parts?: string | readonly (string | number)[]');
});

test("routesDts declares the virtual module and augments the package from a nested block", () => {
  expect(dts(["index.tsx"], "")).toBe(`// Generated by @rezejs/vite-plugin. Do not edit.
declare module "virtual:reze-routes" {
  import type { PathsTree, RouteDefinition } from "@rezejs/router";
  export const routes: readonly RouteDefinition[];
  export const paths: PathsTree;
}
declare module "virtual:reze-routes/register" {
  import type { DataOf } from "@rezejs/router";
  import type { SearchInit } from "@rezejs/router";
  import type { HrefFor } from "@rezejs/router";
  module "@rezejs/router" {
    interface Register {
      paths: "/";
      base: "";
      routes: {
        "/": { params: {}; data: DataOf<import("./routes/index")> };
      };
      pathsTree: { readonly "index": { (search?: SearchInit, hash?: string): HrefFor<"/"> } };
    }
  }
}
`);
});

test("routesModule emits nested lazy imports of absolute files", () => {
  const routes = scanRoutes(["blog.tsx", "blog/[id].tsx", "index.tsx"]);
  expect(routesModule(routes, "/abs/src/routes", "")).toContain(
    'export const routes = [{ id: "blog", path: "/blog", load: () => import("/abs/src/routes/blog.tsx"), children: [' +
      '{ id: "blog/[id]", path: "/:id", load: () => import("/abs/src/routes/blog/[id].tsx") }] }, ' +
      '{ id: "index", path: "/", load: () => import("/abs/src/routes/index.tsx") }];',
  );
});

test("emitted builders round-trip hrefs, including continuations and search", async () => {
  const routes = scanRoutes([
    "index.tsx",
    "blog.tsx",
    "blog/[id].tsx",
    "blog/index.tsx",
    "archive/[[page]].tsx",
    "docs/[...path].tsx",
    "org/[orgId].tsx",
    "org/[orgId]/repo/[name].tsx",
    "pair/[first]/[second].tsx",
    "(auth)/login.tsx",
  ]);
  const file = join(tmpdir(), `reze-paths-${process.pid}.mjs`);
  await writeFile(file, routesModule(routes, "/abs/src/routes", "/app"));
  interface TestNode {
    (...args: readonly unknown[]): unknown;
    [key: string]: TestNode;
  }
  // Dynamic import: the module under test is generated at runtime into a tmp file.
  const paths = (await import(/* @vite-ignore */ "file://" + file)).paths as unknown as TestNode;
  const href = (node: TestNode, ...args: readonly unknown[]): string => (node as (...args: readonly unknown[]) => string)(...args);
  const branch = (node: TestNode, ...args: readonly unknown[]): TestNode => (node as (...args: readonly unknown[]) => TestNode)(...args);
  try {
    expect(href(paths.index)).toBe("/app/");
    expect(href(paths.blog)).toBe("/app/blog");
    expect(href(paths.blog.byId, "1")).toBe("/app/blog/1");
    expect(href(paths.blog.byId, "1", { q: "x" }, "sec")).toBe("/app/blog/1?q=x#sec");
    expect(href(paths.blog.index)).toBe("/app/blog");
    expect(href(paths.byPage)).toBe("/app/archive");
    expect(href(paths.byPage, 2)).toBe("/app/archive/2");
    expect(href(paths.byPath, ["a", "b"])).toBe("/app/docs/a/b");
    expect(href(paths.login)).toBe("/app/login");
    expect(href(branch(paths.byOrgId, "acme").byName, "reze")).toBe("/app/org/acme/repo/reze");
    expect(() => href(paths.bySecond, "a", "b")).toThrow("[reze-router] paths.bySecond has multiple dynamic segments");
  } finally {
    await rm(file, { force: true });
  }
});
