import { expect, test } from "vitest";

import { routesDts, routesModule } from "../src/vite/codegen";
import { scanRoutes } from "../src/vite/scan";

test("routesDts registers every leaf path without the base, deduped and sorted, and the base on its own", () => {
  const dts = routesDts(scanRoutes(["index.tsx", "blog/[id].tsx", "blog/[[page]].tsx", "docs/[...path].tsx"]), "/app/");
  expect(dts).toContain('paths: "/" | "/blog" | "/docs" | `/blog/${string}` | `/docs/${string}`;');
  expect(dts).toContain('base: "/app";');
});

test("a relative or URL base registers the root base, as the browser history does", () => {
  expect(routesDts([], "./")).toContain('base: "";');
  expect(routesDts([], "https://cdn.test/assets/")).toContain('base: "";');
});

test("a catch-all splat registers only its prefix so hrefs stay checked", () => {
  expect(routesDts(scanRoutes(["[...404].tsx", "docs/[...path].tsx"]), "/")).toContain('paths: "/" | "/docs" | `/docs/${string}`;');
});

test("routesDts escapes template characters and falls back to never", () => {
  expect(routesDts(scanRoutes(["a`b/[id].tsx"]), "/")).toContain("paths: `/a\\`b/${string}`;");
  expect(routesDts([], "/")).toContain("paths: never;");
});

test("routesDts declares the virtual module and augments the package from a nested block", () => {
  expect(routesDts(scanRoutes(["index.tsx"]), "/")).toBe(`// Generated by @rezejs/router/vite. Do not edit.
declare module "virtual:reze-routes" {
  import type { RouteDefinition } from "@rezejs/router";
  export const routes: readonly RouteDefinition[];
}
declare module "virtual:reze-routes/register" {
  module "@rezejs/router" {
    interface Register {
      paths: "/";
      base: "";
    }
  }
}
`);
});

test("routesModule emits nested lazy imports of absolute files", () => {
  const routes = scanRoutes(["blog.tsx", "blog/[id].tsx", "index.tsx"]);
  expect(routesModule(routes, "/abs/src/routes")).toBe(
    'export const routes = [{ path: "/blog", load: () => import("/abs/src/routes/blog.tsx"), children: [' +
      '{ path: "/:id", load: () => import("/abs/src/routes/blog/[id].tsx") }] }, ' +
      '{ path: "/", load: () => import("/abs/src/routes/index.tsx") }];\n',
  );
});
