/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Compiles `source`; `null` when nothing in the file is rewritten. Compile errors come back as
 * `error` diagnostics without `code`; the call never throws on them.
 */
export declare function compile(source: string, filename: string, options?: CompileOptions | undefined | null): CompileResult | null

export interface CompileOptions {
  /** Default: `true`. */
  sourceMap?: boolean
  /** Pass `{ name }` to `signal`/`computed` for devtools. Default: `false`. */
  debugNames?: boolean
  /** Register components for hot-swap through `import.meta.hot`. Default: `false`. */
  hot?: boolean
}

export interface CompileResult {
  /** Absent when `diagnostics` holds an `error`. */
  code?: string
  /** Source map v3 JSON. */
  map?: string
  diagnostics: Array<Diagnostic>
}

export interface Diagnostic {
  /** Stable code; see `skills/reze-compiler-diagnostics/SKILL.md`. */
  code: string
  severity: "error" | "warn" | "info"
  /** `[CODE] …`. */
  message: string
  file: string
  start: Position
  end: Position
  /** Enclosing components (`<Name>`) and elements, root first. */
  path: Array<string>
  labels: Array<Label>
  fixes: Array<Fix>
  data: Record<string, string>
  /** Repair guide URL anchored at the code. */
  docs: string
  /** Message, `in` path, location, code frame and fixes. */
  rendered: string
}

/** Replaces source bytes `start..end` with `text`. */
export interface Edit {
  start: number
  end: number
  text: string
}

/** Edits that, applied together, remove the diagnostic. */
export interface Fix {
  title: string
  edits: Array<Edit>
}

export interface Label {
  start: number
  end: number
  message: string
}

export interface Position {
  /** Byte offset. */
  offset: number
  /** 1-based. */
  line: number
  /** 0-based, in UTF-16 code units. */
  column: number
}
