/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Compiles the JSX in `source` to DOM code. Returns `null` when the file has no JSX.
 * `filename` picks the dialect (`.tsx`, `.jsx`, …) and names the source in the map.
 */
export declare function compile(source: string, filename: string, options?: CompileOptions | undefined | null): CompileResult | null

export interface CompileOptions {
  /** Module the generated code imports its runtime from. Default: `"reze-js"`. */
  moduleName?: string
  /** Default: `true`. */
  sourceMap?: boolean
}

export interface CompileResult {
  code: string
  /** Source map v3 JSON. */
  map?: string
}
